version: '3.9'

services:
  django:
    container_name: django
    restart: always
    build: ./server
    env_file:
      - .env
    networks:
      - db_internal
      - web_external
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    gunicorn server.wsgi:application --bind 0.0.0.0:${DJANGO_PORT}"
    environment:
      - DB_HOST=${DB_HOST}
    depends_on:
      - test_mysql

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./static:/usr/src/app/static
    networks:
      - web_external
    ports:
      - "${PORT}:80"
    environment:
      - PORT=${PORT}
      - DJANGO_PORT=${DJANGO_PORT}
    depends_on:
      - django

  test_mysql:
    container_name: test_mysql
    restart: always
    image: mysql
    networks:
      - db_internal
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./initial.sql:/docker-entrypoint-initdb.d/init.sql
      - db_volume:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - TZ=Asia/Seoul

volumes:
  db_volume:

networks:
  db_internal:
    external:
      name: db_internal
  web_external:
    external:
      name: web_external
